# Generated by Django 5.2 on 2025-05-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanrecord',
            options={'ordering': ['-created_at']},
        ),
    ]
